### ISSUE TITLE
[FEATURE REQUEST] - `js` Sandbox APIs

### ISSUE THREAD

**Issue by Aviril** [ov-studio/Vital.sandbox#1]
Embed [**Duktape**](https://duktape.org/) as js engine. Resources could either be `js` or `lua` depending on manifest's config.

**Comment by OvileAmriam** [comment]
> Embed [**Duktape**](https://duktape.org/) as js engine. Resources could either be `js` or `lua` depending on manifest's config.

Embedded `js` successfully for now: https://github.com/ov-studio/Vital.sandbox/blob/main/Sandbox/js/public/vm.h#L23

**Comment by Anisa-Nur** [comment]
Closing since they're exposed already: https://github.com/ov-studio/Vital.sandbox/wiki/API:-JS:-Getting-Started
