### ISSUE TITLE
[BUG] - Type error

### ISSUE THREAD

**Issue by Aviril** [ov-studio/Vital.sandbox#4]
Kindly refer this line: https://github.com/ov-studio/Vital.sandbox/blob/main/Sandbox/lua/index.h#L138
There's a mismatch b/w the invocation & definition of `setMetaTable`

**Comment by Anisa-Nur** [comment]
> Kindly refer this line: https://github.com/ov-studio/Vital.sandbox/blob/main/Sandbox/lua/index.h#L138 There's a mismatch b/w the invocation & definition of `setMetaTable`

Added new overload  to resolve the issue: https://github.com/ov-studio/Vital.sandbox/blob/main/Sandbox/lua/index.h#L103
