### ISSUE TITLE
[Threat Patch] - `Vital::FileSystem::fetchContents()`

### ISSUE THREAD

**Issue by Aviril** [ov-studio/Vital.sandbox#6]
Avoid getting resolved absolute path of the contents (can be abusive), just return the content names inside the folder: https://github.com/ov-studio/Vital.sandbox/blob/main/System/private/filesystem.cpp#L73

**Comment by Anisa-Nur** [comment]
> > Avoid getting resolved absolute path of the contents (can be abusive), just return the content names inside the folder: https://github.com/ov-studio/Vital.sandbox/blob/main/System/private/filesystem.cpp#L73
> 
> Also avoid listing directories with file names, make a flag whether to retrieve either dir or file list

https://github.com/ov-studio/Vital.sandbox/blob/main/System/private/filesystem.cpp#L69
