### ISSUE TITLE
[ENHANCEMENT REQUEST] - Helper function for encryption/decryption handling

### ISSUE THREAD

**Issue by ov-tron** [ov-studio/Vital.sandbox#7]
Make a helper function for those OpenSSL vendor calls to cleanup code as per maintenance purpose: https://github.com/ov-studio/Vital.sandbox/blob/main/System/private/crypto.cpp#L104

**Comment by ov-anisa** [comment]
Implemented: https://github.com/ov-studio/Vital.sandbox/blob/main/System/private/crypto.cpp#L57
