### ISSUE TITLE
[Content-Request] - Sample Resources

### ISSUE THREAD

**Issue by A-Variakojiene** [ov-studio/Vital.sandbox#9]
Proposal for sample resources showcasing how to deal with provided features, APIs in the rightmost way.
Few sample resources could be provided for all supported VMs indicating migration procedure back and forth.

Overlooking current Lua's Async implementation, seems like there's no support for user created 'promises'.
Adding support for custom promises and chaining them would facilitate true Async behaviour for various strategies.
Also kindly consider using a more friendly site instead of git wiki for user's convenience.

**Comment by Aviril** [comment]
We've already planned that. Apparently all VM wrapping are highly in experimental state, do wait for stable release.

Regarding wiki, we'll integrate the existing wiki on remote site.
